name: Clear Cache
on:
  workflow_call:
jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v6
      - name: Run script
        run: scripts/index.js